---
title: "cpgFeatures"
author: "Caitlin Page"
date: "2025-12-10"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---

## Packages

```{r}
library(annotatr)
library(data.table)
library(plyranges)
library(tidyr)
library(stringr)
library(dplyr)
library(ggplot2)
```

## Data Objects
```{r}
cg_sites <- cbind(data.frame(Biostrings::matchPattern("CG", BSgenome.Hsapiens.UCSC.hg38::BSgenome.Hsapiens.UCSC.hg38[["chr22"]])), seqnames = "chr22") %>% 
  mutate(pos = paste0(seqnames, "-", start)) %>%
  relocate(pos, seqnames)
cg_sites$index <- 1:nrow(cg_sites)
```


```{r}
source("../code/processData.R")

for_beta <- readRDS("../output/cluster_files/rrbs_alpha_beta.rds")
for_beta <- for_beta %>% filter(seqnames == "chr22")
rrbs_for_beta_pat <- pat_for_wgbs(for_beta)

for_beta <- for_beta %>% group_by(start) %>% mutate(coverage = n(), mean_alpha = mean(alpha)) %>% ungroup() %>% data.frame()
just_beta <- for_beta %>% distinct(start, beta, coverage, mean_alpha) %>% .[order(.$start),]

```

```{r}
annots <- c("hg38_cpgs")

annotations <- annotatr::build_annotations(genome = 'hg38', annotations = annots)
seqs <- annotations %>% data.frame() %>% distinct(seqnames) %>% .[1:22,]
annotations <- annotations %>% data.frame() %>% filter(seqnames %in% seqs)
annotations %>% 
  ggplot(aes(x = type, fill = type)) +
  geom_bar() +
  theme(legend.position = "none")
```

```{r}
annotations %>% 
  ggplot(aes(x = type, fill = type)) +
  geom_bar() +
  theme(legend.position = "none") +
  facet_wrap(~seqnames)
```

```{r}
find_overlaps(as_granges(for_beta), as_granges(annotations)) %>% data.frame() %>%
  distinct(read_id, alpha, type) %>%
  group_by(read_id) %>%
  mutate(num_feat_read = n()) %>% 
  filter(num_feat_read == 1) %>%
  ggplot(aes(x = type, y = alpha, fill = type)) +
  geom_boxplot() +
  theme(legend.position = "none")

find_overlaps(as_granges(for_beta), as_granges(annotations)) %>% data.frame() %>%
  distinct(read_id, alpha, type) %>%
  group_by(read_id) %>%
  mutate(num_feat_read = n()) %>% 
  filter(num_feat_read == 1) %>%
  ggplot(aes(x = type, y = alpha, fill = type)) +
  geom_violin() +
  theme(legend.position = "none")
```

```{r}
find_overlaps(as_granges(for_beta), as_granges(annotations)) %>% data.frame() %>%
  distinct(read_id, alpha, type) %>%
  group_by(read_id) %>%
  mutate(num_feat_read = n()) %>% 
  filter(num_feat_read == 1) %>%
  ggplot(aes(x = alpha, colour = type)) +
  geom_density() 
```

