---
title: "vizDamefinder"
author: "caitlinpage"
date: "2026-04-17"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---

## Introduction

```{r}
library(DAMEfinder)
```


[workflow](https://bioconductor.org/packages/release/bioc/vignettes/DAMEfinder/inst/doc/DAMEfinder_workflow.html)

[github: methyl_circle_plot()](https://github.com/markrobinsonuzh/DAMEfinder/blob/master/R/methyl_circle_plot.R)

```{r}
library(annotatr)
library(data.table)
library(plyranges)
library(tidyr)
library(stringr)
library(dplyr)
library(ggplot2)
library(edgeR)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
```


```{r}
# all cpg positions
seqs <- seqnames(BSgenome.Hsapiens.UCSC.hg38::BSgenome.Hsapiens.UCSC.hg38)[1:22]

cg_sites <- lapply(seqs, function(x) {
  cbind(data.frame(Biostrings::matchPattern("CG", BSgenome.Hsapiens.UCSC.hg38::BSgenome.Hsapiens.UCSC.hg38[[x]])),
        seqnames = x
  )}) %>% bind_rows()

genes_txdb <- genes(TxDb.Hsapiens.UCSC.hg19.knownGene)
genes_txdb <- filter(genes_txdb, seqnames %in% seqs)
```



```{r}
# load data files
rrbs_alpha_beta <- readRDS("/researchers/caitlin.page/cf_nano/r_output/rrbs_alpha_beta.rds")
gm12878_2 <- readRDS("/researchers/caitlin.page/cf_nano/r_output/rrbs_alpha_beta_rep2.rds")
k562 <- readRDS("/researchers/caitlin.page/cf_nano/r_output/k562_rep1.rds")
k562_2 <- readRDS("/researchers/caitlin.page/cf_nano/r_output/k562_rep2.rds")

# same columns and group samples
cols <- c("read_id", "seqnames", "start", "end", "strand", "meth_status", "meth_pattern", "num_meth", "total", "alpha", "read_start", "read_end", "beta", "sample")

all_samples <- rbind(rrbs_alpha_beta %>% mutate(sample = "b1") %>% .[,cols],
                     gm12878_2 %>% mutate(sample = "b2") %>% .[,cols],
                     k562 %>% mutate(sample = "cml1") %>% .[,cols],
                     k562_2 %>% mutate(sample = "cml2") %>% .[,cols])
```

# define regions
```{r}
all_samples_simp <- all_samples %>% distinct(read_id, seqnames, read_start, read_end, strand, sample, alpha)
colnames(all_samples_simp)[3:4] <- c("start", "end")
```


# steal DAMEFINDER plot

```{r}
  
    # data for points
    d <- data.frame(CpG = rep(cgsite, length(alns.pairs)), 
        read = rep(seq(from = 1, 
        to = length(alns.pairs), by = 1), each = length(cgsite)), 
        value = as.vector(conversion), stringsAsFactors = FALSE)
    
    # data for segments
    reads <- d$read
    
    xstart <- vapply(reads, function(x) {
        newd <- d[which(d$read == x), ]
        vals <- which(!is.na(newd$value))
        min(newd$CpG[vals], snp.start)
    }, FUN.VALUE = double(1))
    
    xend <- vapply(reads, function(x) {
        newd <- d[which(d$read == x), ]
        vals <- which(!is.na(newd$value))
        max(newd$CpG[vals], snp.start)
    }, FUN.VALUE = double(1))
    
    d2 <- unique(data.frame(xstart, xend, reads, stringsAsFactors = FALSE))
    d2$snp <- c(rep("a", length(alt.reads)), rep("r", length(ref.reads)))
    
    # To manually scale the colors
    cols <- c("#0E4071", "#d55e00", "#0E4071", "#d55e00")
    names(cols) <- c("a", "r", alt, ref)
    
    mp <- ggplot() + 
        scale_shape_identity() + 
        theme_void() + 
        geom_segment(data = d2, aes(x = .data$xstart, 
                                    y = .data$reads, 
                                    xend = .data$xend, 
                                    yend = .data$reads,
                                    colour = .data$snp), linewidth = 0.2) + 
        geom_point(data = d, aes(x = .data$CpG,
                                 y = .data$read,
                                 shape = .data$value), 
            fill = "white", size = pointSize) + 
        geom_point(aes(x = snp.start, y = seq(from = 1, to = length(alns.pairs),
            by = 1), shape = letter, colour = letter), size = letterSize) + 
        geom_point(aes(x = cpg.start, y = 0), shape = 24, size = 3, 
            fill = "green") + 
        scale_color_manual(values = cols) + 
        guides(color = FALSE) + 
        ggtitle(sampleName)
```

```{r}
rrbs_plot2 <- function(long_data, read_ids, cpgs = cg_sites, jit_amount = 0.1) {
  set.seed(42) # For reproducibility
  # Calculate a single jitter amount per row (segment)
  long_data <- long_data %>% dplyr::filter(read_id %in% read_ids)
  just_reads <- long_data %>% distinct(read_id, read_start, read_end, alpha)
  jitter_amount <- runif(nrow(just_reads), -jit_amount, jit_amount)
  just_reads$alpha_jit <- just_reads$alpha + jitter_amount
  just_reads <- data.frame(just_reads)
  
  # Add jittered coordinates to new columns in the data frame
  long_data$alpha_jit <- just_reads[match(long_data$read_id, just_reads$read_id), "alpha_jit"]
  long_data$alpha_jit <- as.double(long_data$alpha_jit)
  
    plot <- long_data %>%
      distinct(read_id, read_start, read_end, alpha_jit) %>%
      ggplot() +
      geom_segment(aes(x = read_start, xend = read_end, y = alpha_jit, yend = alpha_jit), alpha = 0.2) +
      geom_point(data = dplyr::filter(long_data, read_id %in% read_ids, start == read_start),
                 aes(x = start, y = alpha_jit, fill = meth_status), shape = 21, color = "black") +
      scale_fill_manual(values = c("U" = "white", "M" = "black")) +
      geom_point(data = distinct(dplyr::filter(long_data, read_id %in% read_ids), start, beta),
                 aes(x = start, y = beta), shape = 4, size = 3) +
      geom_segment(data = filter(cg_sites, start >= min(dplyr::filter(long_data, read_id %in% read_ids)$start),
                                 end <= max(dplyr::filter(long_data, read_id %in% read_ids)$end)),
                   aes(x = start, xend = start, y = -0.15, yend = -0.05), colour = "green")
  plot
}

```

```{r}
rrbs_plot3 <- function(long_data, read_ids, cpgs = cg_sites, jit_amount = 0.1) {
  set.seed(42) # For reproducibility
  # Calculate a single jitter amount per row (segment)
  long_data <- long_data %>% dplyr::filter(read_id %in% read_ids)
  just_reads <- long_data %>% distinct(read_id, read_start, read_end, alpha)
  jitter_amount <- runif(nrow(just_reads), -jit_amount, jit_amount)
  just_reads$alpha_jit <- just_reads$alpha + jitter_amount
  just_reads <- data.frame(just_reads)
  
  # Add jittered coordinates to new columns in the data frame
  long_data$alpha_jit <- just_reads[match(long_data$read_id, just_reads$read_id), "alpha_jit"]
  long_data$alpha_jit <- as.double(long_data$alpha_jit)
  
    plot <- long_data %>%
      distinct(read_id, read_start, read_end, alpha_jit) %>%
      ggplot() +
      geom_segment(aes(x = read_start, xend = read_end, y = alpha_jit, yend = alpha_jit), alpha = 0.2) +
      geom_point(data = dplyr::filter(long_data, read_id %in% read_ids),
               aes(x = start, y = alpha_jit, fill = meth_status), shape = 21, color = "black") +
      scale_fill_manual(values = c("U" = "white", "M" = "black")) +
      geom_point(data = distinct(dplyr::filter(long_data, read_id %in% read_ids), start, beta),
                 aes(x = start, y = beta), shape = 4, size = 3) +
      geom_segment(data = filter(cg_sites, start >= min(dplyr::filter(long_data, read_id %in% read_ids)$start),
                                 end <= max(dplyr::filter(long_data, read_id %in% read_ids)$end)),
                   aes(x = start, xend = start, y = -0.15, yend = -0.05), colour = "green")
  plot
}
```


```{r}
filt_reads <- rrbs_alpha_beta %>% filter(seqnames == "chr1") %>% .[order(.$start),]
```

```{r}
filt_reads[4:130,] %>% distinct(read_id)
```

```{r}
rrbs_plot(filt_reads, filt_reads[4:130,] %>% distinct(read_id) %>% .$read_id, cpgs = cg_sites)
rrbs_plot(filt_reads, filt_reads[4:130,] %>% distinct(read_id) %>% .$read_id, cpgs = cg_sites, count_instead = TRUE)
```
```{r}
reads <- filt_reads[4:130,] %>% distinct(read_id) %>% .$read_id
```

```{r}
rrbs_plot2(filt_reads, reads, cpgs = cg_sites, jit_amount = 0.1)
```


```{r}
rrbs_plot3(filt_reads, reads, cpgs = cg_sites, jit_amount = 0.1) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "coordinate")
```
* nice
* and didn't actually need damefinder - just needed to fix the jitter

```{r}
rrbs_plot3(filt_reads, reads, cpgs = cg_sites, jit_amount = 0.05) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "coordinate")
```

# found a region from old plots
```{r}
reads <- rrbs_alpha_beta %>% filter(seqnames == "chr22", read_start >= 12693800, read_end <= 12694000) %>% distinct(read_id) %>% .$read_id

rrbs_plot3(rrbs_alpha_beta, reads, cpgs = cg_sites, jit_amount = 0.05) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "coordinate")

rrbs_alpha_beta %>% filter(seqnames == "chr22", read_start >= 12693800, read_end <= 12694000) %>% 
  distinct(read_id, alpha) %>%
  mutate(region = "a") %>%
    ggplot(aes(x = region, fill = as.factor(alpha))) +
    geom_bar(position = "fill") 
```

```{r}
reads <- rrbs_alpha_beta %>% filter(seqnames == "chr22", read_start >= 12693600, read_end <= 12693800) %>% distinct(read_id) %>% .$read_id

rrbs_plot3(rrbs_alpha_beta, reads, cpgs = cg_sites, jit_amount = 0.05) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "coordinate")
```


# plot a tile - maybe that will look more like data?
```{r}
library(OpTiles)
rrbs_alpha_beta <- rrbs_alpha_beta %>% group_by(seqnames, start) %>% mutate(coverage = n(), mean_alpha = mean(alpha)) %>% ungroup() %>% data.frame()
just_beta <- rrbs_alpha_beta %>% distinct(seqnames, start, beta, coverage, mean_alpha)

```


```{r}
betavalue <- just_beta$beta
betavalue_df <- as.data.frame(betavalue)
rownames(betavalue_df) <- paste0(just_beta$seqnames, ":", just_beta$start, "-", just_beta$start + 1)

metadata <- "sample_gm12878"
metadata_df <- betavalue_df %>% mutate(sample = "gm12878_1")


for_op <- just_beta %>% mutate(end = start, strand = "*", numCs = beta * coverage, numTs = coverage - numCs, chr = seqnames) %>% .[,c(10,2,6,7,4,8,9)]
mr <- new(
  "methylRaw",
  for_op,
  sample.id = "sample1",
  assembly = "hg38",
  context = "CpG",
  resolution = "base"
)

length_region <- 300
tiles <- methylKit::tileMethylCounts(mr,win.size=length_region,step.size=length_region,cov.bases = 0)

regions_plus_merged_regions <- merging_consecutive_regions(mr, 
                                                           tiles,
                                                           da_thr = length_region,
                                                           cb_thr = length_region)

regions_plus_merged_regions <- regions_plus_merged_regions %>% mutate(width = end - start + 1)
colnames(regions_plus_merged_regions)[1] <- "seqnames"
```

```{r}
just_reads <- rrbs_alpha_beta %>% distinct(read_id, seqnames, read_start, read_end, alpha, total, num_meth)
colnames(just_reads)[3:4] <- c("start", "end")
```


```{r}
find_overlaps(as_granges(regions_plus_merged_regions), as_granges(filter(just_reads, total > 2))) %>% data.frame() %>% 
  group_by(region_id) %>% summarise(n_reads = n(), mean_alpha = mean(alpha), var_alpha = var(alpha)) %>% 
  .[order(.$n_reads, decreasing = TRUE),]

find_overlaps(as_granges(regions_plus_merged_regions), as_granges(filter(just_reads, total > 2))) %>% data.frame() %>% 
  group_by(region_id) %>% summarise(n_reads = n(), mean_alpha = mean(alpha), var_alpha = var(alpha)) %>% filter(n_reads > 30) %>%
  .[order(.$var_alpha, decreasing = TRUE),]
```

```{r}
#chr12:94944001-94944300

reads <- rrbs_alpha_beta %>% filter(seqnames == "chr12", read_start >= 94944001, read_end <= 94944300) %>% distinct(read_id) %>% .$read_id

rrbs_plot3(rrbs_alpha_beta, reads, cpgs = cg_sites, jit_amount = 0.05) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "coordinate")
```
* highest var tile
```{r}
#chrX:149938322-149938621
reads <- rrbs_alpha_beta %>% filter(seqnames == "chrX", read_start >= 149938322, read_end <= 149938621) %>% distinct(read_id) %>% .$read_id

rrbs_plot3(rrbs_alpha_beta, reads, cpgs = cg_sites, jit_amount = 0.05) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "coordinate")
```
*16th tile
```{r}
#chr22:23145601-23145900
reads <- rrbs_alpha_beta %>% filter(seqnames == "chr22", read_start >= 23145601, read_end <= 23145900) %>% distinct(read_id) %>% .$read_id

rrbs_plot3(rrbs_alpha_beta, reads, cpgs = cg_sites, jit_amount = 0.05) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "coordinate")
```


```{r}
rrbs_alpha_beta %>% filter(seqnames == "chr22", read_start >= 23145601, read_end <= 23145900, total > 2) %>% 
  distinct(read_id, alpha) %>%
  mutate(region = "a") %>%
    ggplot(aes(x = region, fill = as.factor(alpha))) +
    geom_bar(position = "fill") 

```

