---
title: "workflow"
author: "caitlinpage"
date: "2026-05-01"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---


```{r}
library(annotatr)
library(data.table)
library(plyranges)
library(tidyr)
library(stringr)
library(dplyr)
library(ggplot2)
library(edgeR)
library(OpTiles)
```

```{r}
seqs <- seqnames(BSgenome.Hsapiens.UCSC.hg38::BSgenome.Hsapiens.UCSC.hg38)[1:22]

cg_sites <- lapply(seqs, function(x) {
        cbind(data.frame(Biostrings::matchPattern("CG", BSgenome.Hsapiens.UCSC.hg38::BSgenome.Hsapiens.UCSC.hg38[[x]])),
            seqnames = x
        )}) %>% bind_rows()
```



```{r}
for_beta_all <- readRDS("/researchers/caitlin.page/cf_nano/r_output/rrbs_alpha_beta.rds")
#for_beta <- readRDS("../output/cluster_files/rrbs_alpha_beta.rds")
for_beta_all <- for_beta_all %>% filter(seqnames %in% seqs)
for_beta_all <- for_beta_all %>% group_by(seqnames, start) %>% mutate(coverage = n(), mean_alpha = mean(alpha)) %>% ungroup() %>% data.frame()
just_beta <- for_beta_all %>% distinct(seqnames, start, beta, coverage, mean_alpha)

rrbs_alpha_beta <- for_beta_all


gm12878_2 <- readRDS("/researchers/caitlin.page/cf_nano/r_output/rrbs_alpha_beta_rep2.rds")
gm12878_2 <- gm12878_2 %>% filter(seqnames %in% seqs)
gm12878_2 <- gm12878_2 %>% group_by(seqnames, start) %>% mutate(coverage = n(), mean_alpha = mean(alpha)) %>% ungroup() %>% data.frame()
just_beta_gm2 <- gm12878_2 %>% distinct(seqnames, start, beta, coverage, mean_alpha)

k562 <- readRDS("/researchers/caitlin.page/cf_nano/r_output/k562_rep1.rds")
k562 <- k562 %>% filter(seqnames %in% seqs)
k562 <- k562 %>% group_by(seqnames, start) %>% mutate(coverage = n(), mean_alpha = mean(alpha)) %>% ungroup() %>% data.frame()
just_beta_k1 <- k562 %>% distinct(seqnames, start, beta, coverage, mean_alpha)

k562_2 <- readRDS("/researchers/caitlin.page/cf_nano/r_output/k562_rep2.rds")
k562_2 <- k562_2 %>% filter(seqnames %in% seqs)
k562_2 <- k562_2 %>% group_by(seqnames, start) %>% mutate(coverage = n(), mean_alpha = mean(alpha)) %>% ungroup() %>% data.frame()
just_beta_k2 <- k562_2 %>% distinct(seqnames, start, beta, coverage, mean_alpha)
```


```{r}
cols <- c("read_id", "seqnames", "start", "end", "strand", "meth_pattern", "meth_status", "num_meth", "total", "alpha", "read_start", "read_end", "beta", "sample")

all_samples <- rbind(rrbs_alpha_beta %>% mutate(sample = "b1") %>% .[,cols], gm12878_2 %>% mutate(sample = "b2") %>% .[,cols], 
                     k562 %>% mutate(sample = "cml1") %>% .[,cols], k562_2 %>% mutate(sample = "cml2") %>% .[,cols])
all_samples_simp <- all_samples %>% distinct(seqnames, read_start, read_end, strand, sample, read_id, alpha, meth_pattern, num_meth, total)
colnames(all_samples_simp)[2:3] <- c("start", "end")
```


# visualise reads
```{r}
source("../code/processData.R")
reads <- rrbs_alpha_beta %>% filter(seqnames == "chr22", read_start >= 12693800, read_end <= 12694000) %>% distinct(read_id) %>% .$read_id

rrbs_plot3(rrbs_alpha_beta, reads, cpgs = cg_sites, jit_amount = 0.05) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "coordinate")

rrbs_alpha_beta %>% filter(seqnames == "chr22", read_start >= 12693800, read_end <= 12694000) %>% 
  distinct(read_id, alpha) %>%
  mutate(region = "a") %>%
    ggplot(aes(x = region, fill = as.factor(alpha))) +
    geom_bar(position = "fill") 
```

# make tiles
```{r, eval=FALSE}
for_op <- rbind(just_beta, just_beta_gm2, just_beta_k1, just_beta_k2) %>% distinct()
for_op <- for_op %>% mutate(end = start, strand = "*", numCs = beta * coverage, numTs = coverage - numCs, chr = seqnames) %>% .[,c(10,2,6,7,4,8,9)]
mr <- new(
  "methylRaw",
  for_op,
  sample.id = "sample1",
  assembly = "hg38",
  context = "CpG",
  resolution = "base"
)

length_region <- 300
tiles <- methylKit::tileMethylCounts(mr,win.size=length_region,step.size=length_region,cov.bases = 0)

tilesdf_all <- methylKit::getData(tiles)

optiles_all <- merging_consecutive_regions(mr, tiles, da_thr = length_region, cb_thr = length_region)

tilesdf_all <- tilesdf_all[,1:4] %>% mutate(width = end - start + 1) 
colnames(tilesdf_all)[1] <- "seqnames"
tilesdf_all$id <- 1:nrow(tilesdf_all)

optiles_all <- optiles_all %>% mutate(width = end - start + 1)
colnames(optiles_all)[1] <- "seqnames"
optiles_all$index <- 1:nrow(optiles_all)
saveRDS(optiles_all, "/researchers/caitlin.page/cf_nano/r_output/optiles_all.rds")
```

```{r}
optiles_all <- readRDS("/researchers/caitlin.page/cf_nano/r_output/optiles_all.rds")
```

```{r}
overlap_pos <- find_overlaps(as_granges(optiles_all), as_granges(all_samples_simp)) %>% data.frame()
```

```{r}
overlap_pos %>% 
  ggplot(aes(x = alpha, colour = sample)) +
  geom_density()

overlap_pos %>% 
  ggplot(aes(x = log2(alpha + 0.1))) +
  geom_density()
```

```{r}
overlap_pos %>% group_by(region_id, sample) %>% summarise(mean_alpha = mean(alpha)) %>%
  ggplot(aes(x = sample, y = mean_alpha)) +
  geom_violin()
```


# DTU tile analysis
```{r, eval=FALSE}
dtu_optile <- find_overlaps(as_granges(all_samples), as_granges(optiles_all)) %>% data.frame() %>%
  distinct(sample, read_id, read_start, read_end, alpha, region_id) %>% 
  mutate(alpha_group = case_when(alpha < 0.2 ~ "a < 0.2",
                                alpha > 0.8 ~ "a > 0.8",
                                alpha >= 0.2 & alpha <= 0.4 ~ "0.2 <= a <= 0.4",
                                alpha > 0.4 & alpha < 0.6 ~ "0.4 < a < 0.6",
                                TRUE ~ "0.6 <= a <= 0.8"))

dtu_optile <- dtu_optile %>% 
  mutate(transcript = paste0(region_id, "_", alpha_group)) %>%
  group_by(sample, transcript) %>%
 summarise(transcript_count = n()) %>% ungroup() %>% data.frame()

# build matrix of "transcript" counts - transcript rows, sample as columns
dtu_optile <- dtu_optile %>% pivot_wider(names_from = sample, values_from = transcript_count)
dtu_optile[is.na(dtu_optile)] <- 0
dtu_optile$gene_id <- sub("_.*", "", dtu_optile$transcript)

# DTU analysis with edgeR
## Alicia prefers gene method over Simes method (documentation slightly confusing about difference)
y <- DGEList(as.matrix(dtu_optile[,2:5]), group = c(1,1,2,2), genes = dtu_optile[,c("gene_id", "transcript")])
design <- model.matrix(~ c(1,1,2,2), data = y$samples)
fit <- glmQLFit(y, design, robust=TRUE)
ds <- diffSpliceDGE(fit, coef = 2, geneid = "gene_id", exonid = "transcript")
ts.gene_optiles <- topSpliceDGE(ds, test = "gene", number = Inf)


# add info to results: get proportion counts
gene_cg <- find_overlaps(as_granges(optiles_all), as_granges(cg_sites)) %>% data.frame() %>%
  group_by(region_id) %>%
  summarise(n_cg = n()) %>%
  ungroup() %>% data.frame()
fit$genes <- fit$genes %>% mutate(n_cg = gene_cg[match(.$gene_id, gene_cg$region_id), "n_cg"])
rpk <- y$counts/rep(fit$genes$n_cg/1000, times = ncol(y$counts))
tpm_mat <- sweep(rpk, 2, colSums(rpk)/1e6, "/")
tpm_mat <- tpm_mat %>% data.frame() %>% mutate(id = dtu_optile$transcript, gene_id = dtu_optile$gene_id)

tpm_mat <- tpm_mat %>%
  group_by(gene_id) %>%
  mutate(prop_S1_gm = b1/sum(b1),
         prop_S2_gm = b2/sum(b2),
         prop_S3_k = cml1/sum(cml1),
         prop_S4_k = cml2/sum(cml2)) %>%
  ungroup() %>% data.frame()


# add locations back in so compatible with plyranges stuff
## this bit only applicable to OPTILES because of the way it structures the ID
ts.gene_optiles <- ts.gene_optiles %>%
  mutate(region_id = gene_id) %>%
  separate_wider_delim(gene_id, delim = ":", names = c("seqnames", "gene_id")) %>%
  mutate(seqnames = gsub("chrchr", "chr", seqnames)) %>%
  separate_wider_delim(gene_id, delim = "-", names = c("start", "end"))
ts.gene_optiles$start <- as.double(ts.gene_optiles$start)
ts.gene_optiles$end <- as.double(ts.gene_optiles$end)
ts.gene_optiles$dtu_rank <- 1:nrow(ts.gene_optiles)
saveRDS(dtu.optiles, "/researchers/caitlin.page/cf_nano/r_output/ts.gene_optiles.rds")
```


```{r}
dtu.optiles <- readRDS("/researchers/caitlin.page/cf_nano/r_output/ts.gene_optiles.rds")
```

```{r}
dtu.gene <- readRDS("/researchers/caitlin.page/cf_nano/r_output/ts.gene.gene.rds")
```

```{r}
annots <- c("hg38_basicgenes", "hg38_genes_intergenic")

annotations <- annotatr::build_annotations(genome = 'hg38', annotations = annots)
seqs <- annotations %>% data.frame() %>% distinct(seqnames) %>% .[1:22,]
annotations <- annotations %>% data.frame() %>% filter(seqnames %in% seqs)

annotations_simp <- annotations %>% group_by(seqnames, symbol, strand) %>% summarise(start = min(start), end = max(end)) %>% ungroup() %>% data.frame()
a <- annotations_simp %>% filter(symbol %in% dtu.gene$gene_id) %>% .[order(.$symbol),] 

dtu.gene <- cbind(dtu.gene %>% filter(gene_id != "XLOC") %>% .[order(.$gene_id),], a)
dtu.gene <- dtu.gene %>% .[order(.$FDR),] %>% mutate(rank = 1:n())
saveRDS(dtu.gene, "/researchers/caitlin.page/cf_nano/r_output/ts.gene.gene.rds")
```

# compare tiles to dtu tiles

```{r}
overlap_pos %>% mutate(dtu = ifelse(region_id %in% dtu.optiles$region_id, TRUE, FALSE)) %>%
  ggplot(aes(x = sample, y = alpha)) +
  geom_violin() +
  facet_wrap(~dtu)
```

```{r}
overlap_pos %>% filter(region_id == "chrchr1:1539808-1540107") %>%
  ggplot(aes(x = sample, y = alpha)) +
  geom_violin()
```

```{r}
source("../code/processData.R")
region <- optiles_all %>% filter(region_id == "chrchr1:1539808-1540107")
reads <- all_samples %>% filter(seqnames == region$seqnames, read_start >= region$start, read_end <= region$end) %>% distinct(read_id) %>% .$read_id

rrbs_plot4(all_samples, reads, cpgs = cg_sites, jit_amount = 0.05) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "coordinate")
```

```{r}
all_samples_simp %>% filter(read_id %in% reads) %>%
  ggplot(aes(x = sample, y = alpha)) +
  geom_violin()
```
```{r}
#chrchr1:1539808-1540107
all_samples %>% distinct(seqnames, start, beta, sample) %>% filter(seqnames == "chr1", start >= 1539808, start <= 1540107) %>%
  ggplot(aes(x = sample, y = beta)) +
  geom_violin()
```



```{r}
overlap_pos %>% filter(index %in% 98410:98420) %>%
  ggplot(aes(x = alpha, colour = sample)) +
  geom_density() +
  facet_wrap(~ index)
```






# compare dtu approaches
```{r}
overlap <- find_overlaps(as_granges(dtu.optiles), as_granges(dtu.gene)) %>% data.frame()
```

```{r}
overlap %>% filter(gene_id == "LRRC4")
```

```{r}
a %>% filter(symbol == "LRRC4") %>%
  ggplot() +
  geom_segment(aes(x = start, xend = end, y = 1, yend = 1)) +
  geom_segment(data = filter(overlap, symbol == "LRRC4"),
               aes(x = start, xend = end, y = 1.2, yend = 1.2, colour = as.factor(dtu_rank)))
```
* I like this: where the dtu tiles are on the gene
```{r}
source("../code/processData.R")
region <- a %>% filter(symbol == "LRRC4")
reads <- rrbs_alpha_beta %>% filter(seqnames == unfactor(region$seqnames), read_start >= region$start, read_end <= region$end) %>% distinct(read_id) %>% .$read_id

rrbs_plot3(rrbs_alpha_beta, reads, cpgs = cg_sites, jit_amount = 0.05) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "coordinate")

rrbs_alpha_beta %>% filter(seqnames == unfactor(region$seqnames), read_start >= region$start, read_end <= region$end) %>% 
  distinct(read_id, alpha) %>%
  mutate(region = "a") %>%
    ggplot(aes(x = region, fill = as.factor(alpha))) +
    geom_bar(position = "fill") 
```

```{r}
source("../code/processData.R")
region <- a %>% filter(symbol == "LRRC4")
reads <- all_samples %>% filter(seqnames == unfactor(region$seqnames), read_start >= region$start, read_end <= region$end) %>% distinct(read_id) %>% .$read_id

rrbs_plot4(all_samples, reads, cpgs = cg_sites, jit_amount = 0.05) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "coordinate")
```
```{r}
overlap %>% filter(symbol == "LRRC4")
```
```{r}
dmrcate_seq_dmr <- readRDS("/researchers/caitlin.page/cf_nano/r_output/dmr_encode_gm12878_k562.rds")
overlap_dmr <- find_overlaps(as_granges(overlap), as_granges(dmrcate_seq_dmr)) %>% data.frame()
```

```{r}
overlap_dmr %>% filter(symbol == "LRRC4")
```


* do for top 5 dtu genes

```{r}
g <- overlap %>% filter(rank <= 5) %>% .[order(.$rank),] %>% .$symbol %>% unique()
a %>% filter(symbol %in% g)
for(i in 1:5) {
p <- a %>% filter(symbol == g[i]) %>%
  ggplot() +
  geom_segment(aes(x = start, xend = end, y = 1, yend = 1)) +
  geom_segment(data = filter(overlap, symbol == g[i]),
               aes(x = start, xend = end, y = 1.2, yend = 1.2, colour = as.factor(dtu_rank))) +
  labs(title = paste0("Gene:", g[i], ", Rank:", i))
print(p)
}
```

* ok and now whatever genes include the top 5 DE tiles

```{r}
g <- overlap %>% filter(dtu_rank <= 5) %>% .[order(.$rank),] %>% .$symbol %>% unique()
for(i in 1:5) {
p <- a %>% filter(symbol == g[i]) %>%
  ggplot() +
  geom_segment(aes(x = start, xend = end, y = 1, yend = 1)) +
  geom_segment(data = filter(overlap, symbol == g[i]),
               aes(x = start, xend = end, y = 1.2, yend = 1.2, colour = as.factor(dtu_rank))) +
  labs(title = paste0("Gene:", g[i], ", Rank:", filter(overlap, symbol == g[i])$rank))
print(p)
}
```


# entropy

```{r}
entropy_gm1 <- read.table("/researchers/caitlin.page/cf_nano/run_metheor/me_ENCFF000LYO.tsv")
colnames(entropy_gm1) <- c("seqnames", "start", "start_2", "start_3", "start_4", "ME")
entropy_gm1[1:10,]
entropy_gm1$end <- entropy_gm1$start_4
```

```{r}
overlap_entropy <- find_overlaps(as_granges(overlap_pos), as_granges(entropy_gm1)) %>% data.frame()
```

```{r}
overlap_entropy %>%
  ggplot(aes(x = ME)) +
  geom_density()
```



```{r}
overlap_entropy %>% mutate(dtu = ifelse(region_id %in% dtu.optiles$region_id, TRUE, FALSE)) %>%
  ggplot(aes(x = dtu, y = ME)) +
  geom_violin()
```

```{r}
overlap_entropy <- overlap_entropy %>% mutate(dtu = ifelse(region_id %in% dtu.optiles$region_id, TRUE, FALSE))
```

```{r}
overlap_entropy %>% filter(index == 7) %>%
  ggplot(aes(x = as.factor(alpha), y = ME, colour = sample)) +
  geom_violin() +
  facet_wrap(~dtu)
```

```{r}
overlap_entropy %>% filter(total > 2, alpha %in% c(0,0.5,1)) %>%
  ggplot(aes(x = as.factor(alpha), y = ME, fill = sample)) +
  geom_violin() +
  facet_wrap(~dtu)
```

